### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by jamescraft10** [GlobedGD/globed2#203]
[2024-07-12_19-50-49.txt](https://github.com/user-attachments/files/16200043/2024-07-12_19-50-49.txt)
![image](https://github.com/user-attachments/assets/acbb7e9a-c9ea-4ce9-bf4d-518c78097b1a)
![image](https://github.com/user-attachments/assets/24586a1e-f788-4dbc-aa3d-e5b3dd0f17a1)

**Comment by jamescraft10** [comment]
only happened once

**Comment by dankmeme01** [comment]
should be fixed in v1.6.0!
