### ISSUE TITLE
[Feature] Make "main-server-url" a persistant and changeable value.

### ISSUE THREAD

**Issue by masckmaster2007** [GlobedGD/globed2#221]
In the case of GDPSes, they can't use main.globed.dev, so they create their own server and instruct people to add said server.

However, a better solution would be to put the GDPS server url as the default without having to build it by yourself (which will get overwritten as soon as you update globed)

A way that could be done would be with a file that will not change regardless of updates, which will contain the main server url.

**Comment by dankmeme01** [comment]
where would the said file be?

i'm not familiar with GDPS, would it be fine if Globed tried reading a file called `globed-server.txt` from the game directory, and if it was found, use the server URL from there?

**Comment by masckmaster2007** [comment]
If it stays persistent through globed updates, yeah.

**Comment by dankmeme01** [comment]
it won't be touched by globed itself, Globed would simply check if a file called "globed-server.txt" exists in the game directory, and read the server URL from there if it does.

This means, if you include the file together with your gdps installation, it will always work across different globed updates

If you have better suggestions, please tell

**Comment by masckmaster2007** [comment]
I don't believe there's a better solution, this already suits well!

**Comment by dankmeme01** [comment]
i was suggesting putting it in the game directory, near the GeometryDash.exe file, but if you have other suggestions then i'n open to ideas

**Comment by masckmaster2007** [comment]
> i was suggesting putting it in the game directory, near the GeometryDash.exe file, but if you have other suggestions then i'n open to ideas

Either mod's folder or inside Resources

**Comment by masckmaster2007** [comment]
any updates?

**Comment by dankmeme01** [comment]
already implemented in the code and will be added in the next update.

to find the URL, the mod will go through all of these in order until one of them is found:

* The `GLOBED_MAIN_SERVER_URL` variable
* `globed-server-url.txt` file in the game folder
* `globed-server-url.txt` file in the mod's config folder
* `globed-server-url.txt` file in the mod's save directory
* The default value, `https://main.globed.dev

**Comment by dankmeme01** [comment]
added in v1.7.1!
