### ISSUE TITLE
i cant press anything after going into someones profile

### ISSUE THREAD

**Issue by Spacezooka** [GlobedGD/globed2#225]
also i dont know who floppyfishh is so idk how i keep going into his levels (the keyboard works but not the mouse for some reason)

https://github.com/user-attachments/assets/05f969ce-4cbf-4ee2-b0a2-8ec95b75223d

idk if the video shows or not

**Comment by dankmeme01** [comment]
is this still an issue on the latest version?

**Comment by Spacezooka** [comment]
i dont think it happens anymore i **think** its fixed

**Comment by dankmeme01** [comment]
closing then, reopen the issue if it happens again
