### ISSUE TITLE
Low textures

### ISSUE THREAD

**Issue by N0VA-The-Git-User** [GlobedGD/globed2#226]
![image](https://github.com/user-attachments/assets/05f8abc8-705c-4f05-a977-62cedefdc920)
Textures only work on low, anything else causes textures to break

**Comment by dankmeme01** [comment]
how does it break exactly? can you show a screenshot?

additionally, if you have any texture packs, please try to disable them, it could be their fault.

**Comment by N0VA-The-Git-User** [comment]
> how does it break exactly? can you show a screenshot?
> 
> additionally, if you have any texture packs, please try to disable them, it could be their fault.

Screenshot is shown on low textures. They jumble up on anything else even when i disable texture packs.

**Comment by dankmeme01** [comment]
i mean show a screenshot of how it looks on medium/high, where it is broken.

and preferrably disable textureldr and make sure there is no `Resources/dankmeme.globed2` folder in your game installation

**Comment by N0VA-The-Git-User** [comment]
> i mean show a screenshot of how it looks on medium/high, where it is broken.
> 
> and preferrably disable textureldr and make sure there is no `Resources/dankmeme.globed2` folder in your game installation

![image](https://github.com/user-attachments/assets/e44f3dcb-1868-4c92-9c8a-95141a4adf99)
On high. I dont know what texture LDR is and there is no Resources/dankmeme.globed2 in my folder

**Comment by N0VA-The-Git-User** [comment]
![image](https://github.com/user-attachments/assets/ac138f28-aacc-47fb-afbd-f0912e94d22d)
High with no texture pack

**Comment by dankmeme01** [comment]
Do you have the "DarkMode V4" mod installed? That mod messes with textures as well, and every Globed update could cause this to happen if you have that mod.

**Comment by dankmeme01** [comment]
stale, closing
