### ISSUE TITLE
players aren't sorted by alphabet

### ISSUE THREAD

**Issue by fbfnysnshnsgnwg** [GlobedGD/globed2#228]
pretty simple.
couldn't upload vid because it was too large, so take this zip with the video inside
[Geometry Dash - 2024-08-01 1-28-34 PM.mp4.zip](https://github.com/user-attachments/files/16840137/Geometry.Dash.-.2024-08-01.1-28-34.PM.mp4.zip)

**Comment by dankmeme01** [comment]
not a bug, this was done because many people would hijack the player list with alt accounts to advertise their levels (by having names starting with zeroes)

**Comment by fbfnysnshnsgnwg** [comment]
oh that was a good choice
