### ISSUE TITLE
crashes on windows

### ISSUE THREAD

**Issue by TGP9063** [GlobedGD/globed2#232]
every time i go get globed and i relaunch the game it crashes idk if this is a bug but if it happens to me it happens to windows users

**Comment by TGP9063** [comment]
[2024-09-03_12-23-00.log](https://github.com/user-attachments/files/16911488/2024-09-03_12-23-00.log)
crash logue

**Comment by dankmeme01** [comment]
fixed in v1.6.2, update globed
