### ISSUE TITLE
PC lags for 10-20 seconds after closing game

### ISSUE THREAD

**Issue by MegaSa1nt** [GlobedGD/globed2#238]
When i close my game with Globed enabled my PC lags for straight 10-20 seconds
https://youtu.be/xVgGQXkXvvk
Disabling assets preloading reduces lags to 5 seconds
You can't hear it on the video, but when closing sound also crumbles

**Comment by dankmeme01** [comment]
could you send a log file (located in `geode/logs/` in the game folder)?

**Comment by MegaSa1nt** [comment]
[Geode 2024-10-16 10.16.28.log](https://github.com/user-attachments/files/17390987/Geode.2024-10-16.10.16.28.log)

**Comment by dankmeme01** [comment]
strange, don't see anything wrong in it. to confirm the issue is really related to textures, can you try to set texture quality to Low, and see if the delay is still long, or if it becomes way shorter?

**Comment by MegaSa1nt** [comment]
sure

**Comment by MegaSa1nt** [comment]
no, still lags same, 
[Geode 2024-10-16 10.25.17.log](https://github.com/user-attachments/files/17391115/Geode.2024-10-16.10.25.17.log)

**Comment by dankmeme01** [comment]
are you sure you changed it? in the previous log the asset preloading took 2.8 seconds, in this one it was 6.8 seconds. On low textures it should be much faster

**Comment by MegaSa1nt** [comment]
https://github.com/user-attachments/assets/3dc4c0eb-e264-4b6b-aa63-e2f8341f90c0

my launcher unfreezes when lags stop

**Comment by dankmeme01** [comment]
not too sure sorry, never encountered this issue before. From the logs can't tell what's the problem, nothing is wrong there

**Comment by MegaSa1nt** [comment]
😔
