### ISSUE TITLE
How to fix this on gd 2.2074 (android) ? 

### ISSUE THREAD

**Issue by JohnnyEnglish83** [GlobedGD/globed2#244]
![Screenshot_20241118-221433](https://github.com/user-attachments/assets/5d6855a0-a84c-4382-8769-406c5181b740)
![Screenshot_20241118-231351](https://github.com/user-attachments/assets/0a3e6585-27b1-45b3-bbc1-b4893caa23e1)

**Comment by dankmeme01** [comment]
mod is not out
