### ISSUE TITLE
Build and Upload new server binaries

### ISSUE THREAD

**Issue by SmilerRyan** [GlobedGD/globed2#246]
Whilst using Geometry Dash v2.2074 and Geode v4.0.1 with Globed v1.7.1 it is no longer possible to connect to the globed game or central servers using the latest version (1.6.2), it is now no longer compatible, and downgrading the addon to the same version is not an option being an older GD/Geode build.

![image](https://github.com/user-attachments/assets/ec509a3d-2416-40f0-ad4f-2500b6912afd)

**Comment by dankmeme01** [comment]
will do as soon as i can get to it, had problems with compiling the server
