### ISSUE TITLE
no me deja entrar 

### ISSUE THREAD

**Issue by jabahub77** [GlobedGD/globed2#247]
al intentar entrar me dise que tiene un error y que quite las texturas, pero cuando lo hago dise que no encuentra la "causa raiz" del problema

**Comment by dankmeme01** [comment]
please speak english.

are you using a modded APK, not from the google play store, that has a texture pack? it is likely incompatible.

**Comment by jabahub77** [comment]
Sorry for not speaking English, but the thing is that I don't play GD on mobile, I play on Windows El 23 nov. 2024 12:53 a. m., dankmeme01 ***@***.***> escribió:
please speak english.
are you using a modded APK, not from the google play store, that has a texture pack? it is likely incompatible.

**Comment by dankmeme01** [comment]
do you have any texture packs installed? if you open the geometry dash folder, inside `Resources` is there a `dankmeme.globed2` folder?

**Comment by jabahub77** [comment]
If I had something that changed the API (I don't know what it is) but that's it, thank you very much for helping me. El 24 nov. 2024 3:22 p. m., dankmeme01 ***@***.***> escribió:
do you have any texture packs installed? if you open the geometry dash folder, inside Resources is there a dankmeme.globed2 folder?

**Comment by dankmeme01** [comment]
i'm not sure what you mean, is the issue resolved?

**Comment by jabahub77** [comment]
Yes, the problem has already been solved, it now lets me in without any problems. El 28 nov. 2024 9:08 a. m., dankmeme01 ***@***.***> escribió:
i'm not sure what you mean, is the issue resolved?
