### ISSUE TITLE
cannot play globed

### ISSUE THREAD

**Issue by meloneater123** [GlobedGD/globed2#251]
i get a error that goes 
"globed error"
Outdated resources were detected. The mod
has been disabled to prevent crashes.

if you have any texture packs, or mods that
change textures, please try disabling then

and when i try to click more info it says 
ERROR
Failed to determine the root cause of the issue
Please create a bug report on our GitHub page
![Screenshot 2024-11-23 195250](https://github.com/user-attachments/assets/bc8d744f-489b-4bdd-9f27-ad667ed6d538)
![Screenshot 2024-11-23 195308](https://github.com/user-attachments/assets/49f7bb42-bf27-4f0a-87d7-16841ffe3904)

**Comment by dankmeme01** [comment]
is this windows/android/macos?

if this is android, are you using GD from play store, or a custom apk that has a texture pack?

**Comment by meloneater123** [comment]
im on windows

**Comment by dankmeme01** [comment]
do you have any texture packs? try to disable them, and try to verify game files in steam

**Comment by dankmeme01** [comment]
reopen the issue if this sill happens on the latest update and without texture packs

**Comment by katana1488** [comment]
what should I do in this situation?(im Russia player)

<img width="1918" height="1079" alt="Image" src="https://github.com/user-attachments/assets/6e95daed-7162-492b-acfb-779b9d8c218d" />

<img width="1917" height="1079" alt="Image" src="https://github.com/user-attachments/assets/dd5ea455-6be5-4042-999f-ac50149f6816" /> 
sometimes:

<img width="1910" height="1072" alt="Image" src="https://github.com/user-attachments/assets/acdd3f80-2491-4c46-9660-0d0b14bb4327" />
sometimes there are no players on the server, and you always get an error message and have to reconnect

**Comment by dankmeme01** [comment]
don't post under unrelated issues, this is due to blocks and usually solved by a vpn or zapret

**Comment by katana1488** [comment]
> Не публикуйте сообщения в разделах, не относящихся к теме, это связано с блокировками и обычно решается с помощью VPN или Zapret.

I wouldn't just post it like that, and neither VPN nor zapret solves the problem

**Comment by katana1488** [comment]
> > Не публикуйте сообщения в разделах, не имеющих отношения к теме, это связано с блокировками и обычно решается с помощью VPN или Zapret.
> 
> Я бы не стал просто так это публиковать, и ни VPN, ни Zapret не решают проблему.
